import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "lt" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Lithuanian translations
const lt: Record<string, string> = {
  // Navigation
  "nav.home": "Pagrindinis",
  "nav.cars": "Automobiliai",
  "nav.leasing": "Lizingas",
  "nav.carPurchase": "Auto supirkimas",
  "nav.about": "Apie mus",
  "nav.partnerZone": "Partnerio zona",
  "nav.dashboard": "Valdymo skydelis",
  "nav.logout": "Atsijungti",

  // Hero section
  "hero.badge": "Paskolos nuo 6.9% metinių palūkanų",
  "hero.title": "Greitas",
  "hero.titleHighlight": "Finansavimas",
  "hero.titleEnd": "be Streso",
  "hero.description": "Platus naudotų automobilių pasirinkimas su finansavimu. Taip pat teikiame paskolas kitoms reikmėms – technikai, remontui ir kt.",
  "hero.viewCars": "Peržiūrėti Automobilius",
  "hero.satisfiedClients": "Patenkintų klientų",
  "hero.decision": "Sprendimas",
  "hero.interestFrom": "Palūkanos nuo",
  "hero.calculator": "Paskolos skaičiuoklė",
  "hero.loanAmount": "Paskolos suma",
  "hero.term": "Terminas",
  "hero.months": "mėn.",
  "hero.monthlyPaymentFrom": "Mėnesio įmoka nuo",
  "hero.calculatorTooltip": "Skaičiuojama su 6.9% metinėmis palūkanomis + 9.50 € mėn. mokestis.",
  "hero.perMonth": "€/mėn.",
  "hero.totalAmount": "Bendra suma",
  "hero.loanConditions": "Kredito sąlygos",
  "hero.annualRate": "Metinė palūkanų norma",
  "hero.loanSum": "Paskolos suma",
  "hero.monthlyFee": "Mėn. mokestis",
  "hero.contractFee": "Sutarties mokestis",
  "hero.bvkmnFrom": "BVKMNN nuo",
  "hero.bvkmnTooltip": "Bendrosios vidutinės kredito kainos metinė norma.",
  "hero.getOffer": "Gauti pasiūlymą",

  // Trust section
  "trust.reliable": "Patikima",
  "trust.reliableDesc": "Visi automobiliai su garantija ir draudimu",
  "trust.experience": "10+ Metų Patirtis",
  "trust.experienceDesc": "Ilgametė patirtis automobilių rinkoje",
  "trust.lowRates": "Žemos Palūkanos",
  "trust.lowRatesDesc": "Konkurencingos palūkanų normos nuo 3.9% metinių",
  "trust.fastProcess": "Greitas Procesas",
  "trust.fastProcessDesc": "Finansavimas per 30 min",

  // Featured cars
  "featured.title": "Siūlomi Automobiliai",
  "featured.description": "Peržiūrėkite mūsų rekomenduojamus automobilius su patraukliu finansavimu",
  "featured.viewAll": "Visi automobiliai",
  "featured.viewPlatforms": "Peržiūrėkite mūsų automobilius",
  "featured.viewListings": "Peržiūrėti skelbimus",
  "featured.recommended": "AUTOKOPERS rekomenduoja",

  // Car card
  "car.year": "Metai",
  "car.mileage": "Rida",
  "car.fuel": "Kuras",
  "car.view": "Peržiūrėti",
  "car.monthlyFrom": "Nuo",
  "car.perMonthShort": "/mėn.",

  // Financing section
  "financing.title": "Finansavimo Sprendimai",
  "financing.description": "Individualūs finansavimo planai, pritaikyti jūsų poreikiams",
  "financing.flexiblePlans": "Lankstūs Planai",
  "financing.flexiblePlansDesc": "Pritaikyta finansavimo tvarka pagal jūsų galimybes",
  "financing.lowRates": "Žemos Palūkanos",
  "financing.lowRatesDesc": "Konkurencingos palūkanų normos nuo 3.9% metinių",
  "financing.quickApproval": "Patvirtinimas per 1 val",
  "financing.quickApprovalDesc": "Greitas paraiškos nagrinėjimas ir atsakymas",
  "financing.calculate": "Apskaičiuoti mėnesinę įmoką",

  // Testimonials
  "testimonials.title": "Mūsų klientai sako",
  "testimonials.description": "Tūkstančiai patenkintų klientų jau rado savo automobilį",

  // Footer
  "footer.companyDesc": "Patikimas automobilių finansavimo partneris su ilgamete patirtimi rinkoje.",
  "footer.navigation": "Navigacija",
  "footer.contact": "Kontaktai",
  "footer.workingHours": "Darbo laikas",
  "footer.weekdays": "I-V: 9:00 - 18:00",
  "footer.saturday": "VI: 10:00 - 15:00",
  "footer.sunday": "VII: Nedirbame",
  "footer.rights": "Visos teisės saugomos.",

  // Contact section
  "contact.title": "Susisiekite",
  "contact.description": "Turite klausimų? Susisiekite su mumis!",
  "contact.email": "El. paštas",
  "contact.phone": "Telefonas",
  "contact.address": "Adresas",

  // Auth
  "auth.partnerLogin": "Partnerio prisijungimas",
  "auth.login": "Prisijungti",
  "auth.signup": "Registruotis",
  "auth.email": "El. paštas",
  "auth.password": "Slaptažodis",
  "auth.fullName": "Vardas Pavardė",
  "auth.forgotPassword": "Pamiršote slaptažodį?",
  "auth.resetPassword": "Atkurti slaptažodį",
  "auth.backToLogin": "Grįžti prie prisijungimo",
  "auth.sendResetLink": "Siųsti atkūrimo nuorodą",
  "auth.noAccount": "Neturite paskyros?",
  "auth.hasAccount": "Jau turite paskyrą?",
  "auth.signupSuccess": "Registracija sėkminga!",
  "auth.loginSuccess": "Sėkmingai prisijungėte!",
  "auth.resetEmailSent": "Atkūrimo nuoroda išsiųsta į el. paštą",

  // Partner Dashboard
  "dashboard.title": "Valdymo skydelis",
  "dashboard.myListings": "Mano skelbimai",
  "dashboard.newListing": "Naujas skelbimas",
  "dashboard.totalListings": "Viso skelbimų",
  "dashboard.webVisible": "Rodomi Web",
  "dashboard.autopliusVisible": "Rodomi Autoplius",
  "dashboard.unpublished": "Nepublikuota",
  "dashboard.search": "Ieškoti pagal markę ar modelį...",
  "dashboard.noListings": "Skelbimų nerasta",
  "dashboard.createFirst": "Sukurkite pirmą skelbimą",

  // Create listing
  "listing.edit": "Redaguoti skelbimą",
  "listing.new": "Naujas skelbimas",
  "listing.importFromAutoplius": "Importuoti iš Autoplius",
  "listing.importDesc": "Įklijuokite skelbimo nuorodą iš autoplius.lt ir automatiškai užpildysime formą",
  "listing.import": "Importuoti",
  "listing.importing": "Importuojama...",
  "listing.basicInfo": "Pagrindinė informacija",
  "listing.make": "Markė",
  "listing.model": "Modelis",
  "listing.year": "Metai",
  "listing.price": "Kaina (€)",
  "listing.mileage": "Rida (km)",
  "listing.fuelType": "Kuro tipas",
  "listing.transmission": "Pavarų dėžė",
  "listing.bodyType": "Kėbulo tipas",
  "listing.engineCapacity": "Variklio tūris (l)",
  "listing.power": "Galia (kW)",
  "listing.doors": "Durų skaičius",
  "listing.seats": "Sėdimų vietų",
  "listing.color": "Spalva",
  "listing.steeringWheel": "Vairas",
  "listing.condition": "Būklė",
  "listing.vin": "VIN kodas",
  "listing.defects": "Defektai",
  "listing.description": "Aprašymas",
  "listing.photos": "Nuotraukos",
  "listing.dropPhotos": "Nutempkite nuotraukas čia arba",
  "listing.selectPhotos": "pasirinkite failus",
  "listing.visibility": "Matomumas",
  "listing.visibleOnWeb": "Rodyti svetainėje",
  "listing.visibleOnAutoplius": "Rodyti Autoplius",
  "listing.featured": "Rekomenduojamas",
  "listing.recommended": "Išskirtinis",
  "listing.companyCar": "Įmonės automobilis",
  "listing.save": "Išsaugoti",
  "listing.saving": "Saugoma...",
  "listing.cancel": "Atšaukti",
  "listing.created": "Skelbimas sukurtas!",
  "listing.updated": "Skelbimas atnaujintas!",
  "listing.deleted": "Skelbimas ištrintas!",
  "listing.deleteConfirm": "Ar tikrai norite ištrinti šį skelbimą?",

  // Car detail
  "carDetail.backToList": "Grįžti į sąrašą",
  "carDetail.specifications": "Specifikacijos",
  "carDetail.features": "Įranga",
  "carDetail.description": "Aprašymas",
  "carDetail.financing": "Finansavimas",
  "carDetail.monthlyPayment": "Mėnesio įmoka",
  "carDetail.applyNow": "Pateikti paraišką",
  "carDetail.contactUs": "Susisiekite",

  // Leasing page
  "leasing.title": "Lizingas",
  "leasing.description": "Automobilių lizingas su palankiausiomis sąlygomis",

  // Old car purchase keys (kept for backwards compatibility with old components)
  "carPurchase.title": "Auto supirkimas",
  "carPurchase.description": "Superkame automobilius greitai ir brangiai",
  "carPurchase.instantEval": "Momentinė įvertinimas",
  "carPurchase.instantEvalDesc": "Gausite automobilio vertinimą per kelias minutes",
  "carPurchase.bestPrice": "Geriausia kaina",
  "carPurchase.bestPriceDesc": "Siūlome konkurencingas kainas už jūsų automobilį",
  "carPurchase.quickDeal": "Greitas sandoris",
  "carPurchase.quickDealDesc": "Visas procesas užtrunka vos kelias valandas",
  "carPurchase.safeDeal": "Saugus sandoris",
  "carPurchase.safeDealDesc": "Oficialus sandoris su visais dokumentais",
  "carPurchase.howItWorks": "Kaip tai veikia",
  "carPurchase.step1": "Pateikite užklausą",
  "carPurchase.step1Desc": "Užpildykite formą su automobilio duomenimis",
  "carPurchase.step2": "Gausite vertinimą",
  "carPurchase.step2Desc": "Mūsų specialistai įvertins automobilį",
  "carPurchase.step3": "Susitarkime",
  "carPurchase.step3Desc": "Suderinę kainą, sudarome sandorį",
  "carPurchase.step4": "Gaukite pinigus",
  "carPurchase.step4Desc": "Pinigai pervedami iš karto",
  "carPurchase.orCall": "arba skambinkite",

  // About page
  "about.title": "Apie mus",
  "about.description": "Patikimas automobilių finansavimo partneris",

  // Car catalog
  "catalog.title": "Automobilių katalogas",
  "catalog.filter": "Filtruoti",
  "catalog.clearFilters": "Išvalyti filtrus",
  "catalog.noResults": "Automobilių nerasta",
  "catalog.adjustFilters": "Pakeiskite filtrus arba",
  "catalog.viewAll": "peržiūrėkite visus",

  // Loan form
  "loan.title": "Paskolos paraiška",
  "loan.name": "Vardas Pavardė",
  "loan.email": "El. paštas",
  "loan.phone": "Telefonas",
  "loan.amount": "Paskolos suma",
  "loan.term": "Terminas",
  "loan.monthlyPayment": "Mėnesio įmoka",
  "loan.submit": "Pateikti paraišką",
  "loan.submitting": "Siunčiama...",
  "loan.success": "Paraiška išsiųsta sėkmingai!",

  // Cookie consent
  "cookie.message": "Ši svetainė naudoja slapukus, kad pagerintų jūsų patirtį.",
  "cookie.title": "Slapukų politika",
  "cookie.description": "Naudojame slapukus, kad pagerintume jūsų naršymo patirtį ir analizuotume svetainės lankomumą. Sutikdami padėsite mums tobulinti paslaugas.",
  "cookie.accept": "Sutinku",
  "cookie.decline": "Atmesti",

  // Loan calculator
  "loanCalc.title": "Lizingo skaičiuoklė",
  "loanCalc.carPrice": "Automobilio kaina",
  "loanCalc.downPayment": "Pradinis įnašas",
  "loanCalc.noDownPayment": "Be pradinio įnašo",
  "loanCalc.customAmount": "Kita suma",
  "loanCalc.enterAmount": "Įveskite sumą",
  "loanCalc.period": "Laikotarpis",
  "loanCalc.months": "mėn.",
  "loanCalc.totalAmount": "Bendra suma",
  "loanCalc.monthlyPayment": "Mėnesinė įmoka",
  "loanCalc.submitApplication": "Pateikti lizingo paraišką",
  "loanCalc.disclaimer": "* Skaičiavimas orientacinis. Tikslias sąlygas sužinosite pateikę lizingo paraišką. Metinė palūkanų norma:",
  "loanCalc.from": "nuo",
  "loanCalc.perMonth": "/mėn.",

  // Loan application form
  "loanApp.title": "Paskolos paraiška",
  "loanApp.name": "Vardas, Pavardė",
  "loanApp.namePlaceholder": "Vardenis Pavardenis",
  "loanApp.email": "El. paštas",
  "loanApp.emailPlaceholder": "vardas@example.com",
  "loanApp.phone": "Telefonas",
  "loanApp.phonePlaceholder": "+370 600 00000",
  "loanApp.leasingData": "Lizingo duomenys:",
  "loanApp.car": "Automobilis:",
  "loanApp.amount": "Suma:",
  "loanApp.term": "Terminas:",
  "loanApp.monthlyPayment": "Mėn. įmoka:",
  "loanApp.submit": "Pateikti paraišką",
  "loanApp.submitting": "Siunčiama...",
  "loanApp.success": "Paraiška pateikta!",
  "loanApp.successDesc": "Netrukus susisieksime su jumis el. paštu arba telefonu.",
  "loanApp.error": "Klaida pateikiant paraišką. Bandykite dar kartą.",

  // Leasing page
  "leasing.heroTitle": "Finansavimas",
  "leasing.heroDesc": "Greitas ir paprastas procesas – gaukite finansavimą per 24 valandas su žemiausiomis palūkanomis rinkoje",
  "leasing.calcTitle": "Paskaičiuokite mėnesinę įmoką",
  "leasing.calcDesc": "Naudokite skaičiuoklę ir sužinokite preliminarią mėnesinę įmoką",
  "leasing.loanCalculator": "Paskolos skaičiuoklė",
  "leasing.loanAmount": "Paskolos suma",
  "leasing.term": "Terminas",
  "leasing.monthlyFrom": "Mėnesio įmoka nuo",
  "leasing.calculatorTooltip": "Skaičiuojama su 6.9% metinėmis palūkanomis + 9.50 € mėn. mokestis.",
  "leasing.totalReturn": "Bendra grąžintina suma:",
  "leasing.conditions": "Kredito sąlygos",
  "leasing.annualRate": "Metinė palūkanų norma",
  "leasing.loanSum": "Paskolos suma",
  "leasing.termRange": "Terminas",
  "leasing.adminFee": "Mėn. administravimo mokestis",
  "leasing.contractFee": "Sutarties mokestis",
  "leasing.bvkmn": "BVKMNN nuo",
  "leasing.bvkmnTooltip": "Bendrosios vidutinės kredito kainos metinė norma.",
  "leasing.submitApplication": "Pateikti paraišką",
  "leasing.howItWorks": "Kaip veikia finansavimas?",
  "leasing.step1": "Užpildykite paraišką",
  "leasing.step1Desc": "Nurodykite paskolos sumą ir terminą",
  "leasing.step2": "Gaukite pasiūlymą",
  "leasing.step2Desc": "Atsakymas per 24 val.",
  "leasing.step3": "Pasirašykite sutartį",
  "leasing.step3Desc": "Patogiai internetu",
  "leasing.step4": "Gaukite pinigus",
  "leasing.step4Desc": "Tiesiogiai į sąskaitą",
  "leasing.step": "Žingsnis",
  "leasing.whyChoose": "Kodėl rinktis mus?",
  "leasing.benefit1": "Palyginame sąlygas",
  "leasing.benefit1Desc": "Surandame geriausią pasiūlymą iš kelių finansų partnerių",
  "leasing.benefit2": "Žemos palūkanos",
  "leasing.benefit2Desc": "Konkurencingos palūkanų normos nuo 6.9% metinių",
  "leasing.benefit3": "Greitas sprendimas",
  "leasing.benefit3Desc": "Atsakymas per 24 valandas, pinigai - per 1-2 dienas",
  "leasing.benefit4": "Individuali konsultacija",
  "leasing.benefit4Desc": "Padėsime pasirinkti tinkamiausią finansavimo variantą",
  "leasing.readyToStart": "Pasiruošę pradėti?",
  "leasing.readyToStartDesc": "Užpildykite paraišką dabar ir gaukite pasiūlymą per 24 valandas",
  "leasing.getOffer": "Gauti pasiūlymą",

  // About page
  "about.heroTitle": "Apie mus",
  "about.heroDesc": "Jūsų patikimas partneris automobilio finansavimo srityje",
  "about.whoWeAre": "Kas mes esame?",
  "about.desc1": "Esame komanda, kuri rūpinasi ne tik pardavimu, bet ir visu procesu – nuo poreikių įvertinimo ir automobilio paieškos iki sklandaus finansavimo bei dokumentų sutvarkymo. Mums svarbiausia – skaidrumas ir aiški komunikacija, todėl viską paaiškiname paprastai ir be paslėptų sąlygų.",
  "about.desc2": "Turime patikrintų partnerių tinklą Lietuvoje ir užsienyje, todėl galime pasiūlyti tiek čia esančius automobilius, tiek individualią paiešką visoje Europoje. Kiekvieną automobilį tikriname atsakingai, o sprendimus pritaikome pagal kliento situaciją.",
  "about.mission": "Mūsų misija",
  "about.missionDesc": "Suteikti kiekvienam galimybę įsigyti automobilį su patogiu ir lanksčiu finansavimu, užtikrinant skaidrumą ir patikimumą visame procese.",
  "about.values": "Mūsų vertybės",
  "about.valuesDesc": "Sąžiningumas, profesionalumas ir klientų pasitenkinimas – tai vertybės, kuriomis grindžiame savo veiklą kiekvieną dieną.",
  "about.whyChoose": "Kodėl pasirinkti mus?",
  "about.reliability": "Patikimumas",
  "about.reliabilityDesc": "Visi automobiliai patikrinti ir su garantija",
  "about.experience": "10+ metų patirtis",
  "about.experienceDesc": "Ilgametė patirtis automobilių rinkoje",
  "about.flexFinancing": "Lankstus finansavimas",
  "about.flexFinancingDesc": "Individualūs sprendimai kiekvienam klientui",
  "about.contactTitle": "Susisiekite su mumis",
  "about.contactDesc": "Turite klausimų? Mūsų komanda pasiruošusi padėti!",
  "about.contact": "Susisiekti",
  "about.getOffer": "Gauti pasiūlymą",
  "about.contactForm": "Susisiekite su mumis",
  "about.name": "Vardas",
  "about.yourName": "Jūsų vardas",
  "about.email": "El. paštas",
  "about.phone": "Telefonas",
  "about.message": "Žinutė",
  "about.messagePlaceholder": "Jūsų klausimas ar žinutė...",
  "about.send": "Siųsti žinutę",
  "about.sending": "Siunčiama...",
  "about.orContact": "Arba susisiekite tiesiogiai:",
  "about.messageSent": "Žinutė išsiųsta!",
  "about.messageSentDesc": "Susisieksime su jumis artimiausiu metu.",
  "about.messageError": "Nepavyko išsiųsti žinutės. Bandykite dar kartą.",

  // Car purchase page
  "carPurchase.heroTitle": "Auto supirkimas",
  "carPurchase.heroDesc": "Greitai ir sąžiningai superkame visų markių automobilius",
  "carPurchase.whySell": "Kodėl parduoti mums?",
  "carPurchase.whySellDesc": "Superkame automobilius greitai, sąžiningai ir už geriausią kainą",
  "carPurchase.bestPrices": "Geriausios kainos",
  "carPurchase.bestPricesDesc": "Siūlome konkurencingas kainas už jūsų automobilį",
  "carPurchase.fastProcess": "Greitas procesas",
  "carPurchase.fastProcessDesc": "Automobilio įvertinimas ir pirkimas per 24 valandas",
  "carPurchase.reliableDeal": "Patikimas sandoris",
  "carPurchase.reliableDealDesc": "Skaidrus ir saugus automobilio supirkimo procesas",
  "carPurchase.anyCondition": "Bet kokia būklė",
  "carPurchase.anyConditionDesc": "Perkame automobilius įvairių markių ir bet kokios būklės",
  "carPurchase.howWorks": "Kaip tai veikia?",
  "carPurchase.simpleProcess": "Paprastas ir greitas procesas",
  "carPurchase.stepContact": "Susisiekite",
  "carPurchase.stepContactDesc": "Paskambinkite mums arba užpildykite formą internete su automobilio duomenimis",
  "carPurchase.stepEval": "Įvertinimas",
  "carPurchase.stepEvalDesc": "Mūsų specialistas apžiūri automobilį ir pateikia kainą",
  "carPurchase.stepDeal": "Sandoris",
  "carPurchase.stepDealDesc": "Sutarę dėl kainos, atliekame visus formalumus ir atsiskaitome",
  "carPurchase.wantToSell": "Norite parduoti automobilį?",
  "carPurchase.wantToSellDesc": "Susisiekite su mumis šiandien ir gaukite geriausią pasiūlymą!",
  "carPurchase.call": "Paskambinkite",
  "carPurchase.workingHours": "Darbo laikas",
  "carPurchase.submitRequest": "Pateikti užklausą",

  // Sell your car page
  "sellCar.heroTitle": "Parduosime tavo automobilį",
  "sellCar.heroDesc": "Palik savo automobilį parduoti pas mus ir gauk maksimalų rezultatą be vargo. Mes pasirūpinsime viskuo: nuo profesionalių nuotraukų ir skelbimų iki derybų su pirkėjais ir dokumentų sutvarkymo.",
  "sellCar.submitRequest": "Pateikti užklausą",
  "sellCar.howWorks": "Kaip tai veikia?",
  "sellCar.step1": "Užklausa",
  "sellCar.step1Desc": "Užpildyk formą su automobilio informacija",
  "sellCar.step2": "Įvertinimas",
  "sellCar.step2Desc": "Susisiekiame ir įvertiname automobilį",
  "sellCar.step3": "Pardavimas",
  "sellCar.step3Desc": "Skelbiame, rodome ir deramės su pirkėjais",
  "sellCar.step4": "Išmokėjimas",
  "sellCar.step4Desc": "Sutvarkome dokumentus ir išmokame pinigus",
  "sellCar.whyChoose": "Kodėl pasirinkti mus?",
  "sellCar.professional": "Profesionalios paslaugos",
  "sellCar.professionalDesc": "Profesionalios nuotraukos, detalūs skelbimai ir aktyvus rinkodaros darbas užtikrina, kad tavo automobilis pasiektų kuo platesnę auditoriją.",
  "sellCar.timeSaved": "Sutaupytas laikas",
  "sellCar.timeSavedDesc": "Nereikia pačiam rašyti skelbimų, atsakinėti į žinutes, rodyti automobilio ar derėtis su pirkėjais – visa tai darome mes.",
  "sellCar.safety": "Saugumas",
  "sellCar.safetyDesc": "Patikrinami pirkėjai, saugus pinigų perdavimas ir pilnas dokumentų sutvarkymas. Tau nereikia jaudintis dėl sukčiavimo ar biurokratijos.",
  "sellCar.bestPrice": "Geriausia kaina",
  "sellCar.bestPriceDesc": "Padedame nustatyti optimalią kainą, kuri užtikrina greitą pardavimą ir maksimalią naudą tau. 10+ metų patirtis automobilių rinkoje.",
  "sellCar.readyToSell": "Pasiruošęs parduoti?",
  "sellCar.readyToSellDesc": "Komisinis mokestis suderinamas individualiai, priklausomai nuo automobilio ir paslaugų apimties. Susisiek ir sužinok daugiau!",

  // Common
  "common.loading": "Kraunama...",
  "common.error": "Klaida",
  "common.success": "Sėkmingai!",
  "common.save": "Išsaugoti",
  "common.cancel": "Atšaukti",
  "common.delete": "Ištrinti",
  "common.edit": "Redaguoti",
  "common.back": "Grįžti",
  "common.next": "Toliau",
  "common.previous": "Atgal",
  "common.search": "Ieškoti",
  "common.filter": "Filtruoti",
  "common.all": "Visi",
  "common.yes": "Taip",
  "common.no": "Ne",
};

// English translations
const en: Record<string, string> = {
  // Navigation
  "nav.home": "Home",
  "nav.cars": "Cars",
  "nav.leasing": "Leasing",
  "nav.carPurchase": "Car Purchase",
  "nav.about": "About",
  "nav.partnerZone": "Partner Zone",
  "nav.dashboard": "Dashboard",
  "nav.logout": "Logout",

  // Hero section
  "hero.badge": "Loans from 6.9% annual interest",
  "hero.title": "Fast",
  "hero.titleHighlight": "Financing",
  "hero.titleEnd": "Without Stress",
  "hero.description": "Wide selection of used cars with financing. We also provide loans for other needs – equipment, repairs, etc.",
  "hero.viewCars": "View Cars",
  "hero.satisfiedClients": "Satisfied clients",
  "hero.decision": "Decision",
  "hero.interestFrom": "Interest from",
  "hero.calculator": "Loan Calculator",
  "hero.loanAmount": "Loan amount",
  "hero.term": "Term",
  "hero.months": "mo.",
  "hero.monthlyPaymentFrom": "Monthly payment from",
  "hero.calculatorTooltip": "Calculated with 6.9% annual interest + €9.50 monthly fee.",
  "hero.perMonth": "€/mo.",
  "hero.totalAmount": "Total amount",
  "hero.loanConditions": "Loan Conditions",
  "hero.annualRate": "Annual interest rate",
  "hero.loanSum": "Loan amount",
  "hero.monthlyFee": "Monthly fee",
  "hero.contractFee": "Contract fee",
  "hero.bvkmnFrom": "APR from",
  "hero.bvkmnTooltip": "Annual Percentage Rate of Charge.",
  "hero.getOffer": "Get an offer",

  // Trust section
  "trust.reliable": "Reliable",
  "trust.reliableDesc": "All cars with warranty and insurance",
  "trust.experience": "10+ Years Experience",
  "trust.experienceDesc": "Long-term experience in the car market",
  "trust.lowRates": "Low Rates",
  "trust.lowRatesDesc": "Competitive interest rates from 3.9% annually",
  "trust.fastProcess": "Fast Process",
  "trust.fastProcessDesc": "Financing in 30 min",

  // Featured cars
  "featured.title": "Featured Cars",
  "featured.description": "Browse our recommended cars with attractive financing",
  "featured.viewAll": "All cars",
  "featured.viewPlatforms": "View our cars",
  "featured.viewListings": "View listings",
  "featured.recommended": "AUTOKOPERS recommends",

  // Car card
  "car.year": "Year",
  "car.mileage": "Mileage",
  "car.fuel": "Fuel",
  "car.view": "View",
  "car.monthlyFrom": "From",
  "car.perMonthShort": "/mo.",

  // Financing section
  "financing.title": "Financing Solutions",
  "financing.description": "Individual financing plans tailored to your needs",
  "financing.flexiblePlans": "Flexible Plans",
  "financing.flexiblePlansDesc": "Financing terms adjusted to your capabilities",
  "financing.lowRates": "Low Rates",
  "financing.lowRatesDesc": "Competitive interest rates from 3.9% annually",
  "financing.quickApproval": "Approval in 1 hour",
  "financing.quickApprovalDesc": "Quick application review and response",
  "financing.calculate": "Calculate monthly payment",

  // Testimonials
  "testimonials.title": "What our clients say",
  "testimonials.description": "Thousands of satisfied clients have found their car",

  // Footer
  "footer.companyDesc": "Reliable car financing partner with long-term market experience.",
  "footer.navigation": "Navigation",
  "footer.contact": "Contact",
  "footer.workingHours": "Working Hours",
  "footer.weekdays": "Mon-Fri: 9:00 - 18:00",
  "footer.saturday": "Sat: 10:00 - 15:00",
  "footer.sunday": "Sun: Closed",
  "footer.rights": "All rights reserved.",

  // Contact section
  "contact.title": "Contact Us",
  "contact.description": "Have questions? Get in touch with us!",
  "contact.email": "Email",
  "contact.phone": "Phone",
  "contact.address": "Address",

  // Auth
  "auth.partnerLogin": "Partner Login",
  "auth.login": "Login",
  "auth.signup": "Sign Up",
  "auth.email": "Email",
  "auth.password": "Password",
  "auth.fullName": "Full Name",
  "auth.forgotPassword": "Forgot password?",
  "auth.resetPassword": "Reset Password",
  "auth.backToLogin": "Back to login",
  "auth.sendResetLink": "Send reset link",
  "auth.noAccount": "Don't have an account?",
  "auth.hasAccount": "Already have an account?",
  "auth.signupSuccess": "Registration successful!",
  "auth.loginSuccess": "Successfully logged in!",
  "auth.resetEmailSent": "Reset link sent to your email",

  // Partner Dashboard
  "dashboard.title": "Dashboard",
  "dashboard.myListings": "My Listings",
  "dashboard.newListing": "New Listing",
  "dashboard.totalListings": "Total listings",
  "dashboard.webVisible": "Visible on Web",
  "dashboard.autopliusVisible": "Visible on Autoplius",
  "dashboard.unpublished": "Unpublished",
  "dashboard.search": "Search by make or model...",
  "dashboard.noListings": "No listings found",
  "dashboard.createFirst": "Create your first listing",

  // Create listing
  "listing.edit": "Edit Listing",
  "listing.new": "New Listing",
  "listing.importFromAutoplius": "Import from Autoplius",
  "listing.importDesc": "Paste the listing URL from autoplius.lt to auto-fill the form",
  "listing.import": "Import",
  "listing.importing": "Importing...",
  "listing.basicInfo": "Basic Information",
  "listing.make": "Make",
  "listing.model": "Model",
  "listing.year": "Year",
  "listing.price": "Price (€)",
  "listing.mileage": "Mileage (km)",
  "listing.fuelType": "Fuel Type",
  "listing.transmission": "Transmission",
  "listing.bodyType": "Body Type",
  "listing.engineCapacity": "Engine Capacity (l)",
  "listing.power": "Power (kW)",
  "listing.doors": "Doors",
  "listing.seats": "Seats",
  "listing.color": "Color",
  "listing.steeringWheel": "Steering Wheel",
  "listing.condition": "Condition",
  "listing.vin": "VIN Code",
  "listing.defects": "Defects",
  "listing.description": "Description",
  "listing.photos": "Photos",
  "listing.dropPhotos": "Drop photos here or",
  "listing.selectPhotos": "select files",
  "listing.visibility": "Visibility",
  "listing.visibleOnWeb": "Show on website",
  "listing.visibleOnAutoplius": "Show on Autoplius",
  "listing.featured": "Recommended",
  "listing.recommended": "Featured",
  "listing.companyCar": "Company car",
  "listing.save": "Save",
  "listing.saving": "Saving...",
  "listing.cancel": "Cancel",
  "listing.created": "Listing created!",
  "listing.updated": "Listing updated!",
  "listing.deleted": "Listing deleted!",
  "listing.deleteConfirm": "Are you sure you want to delete this listing?",

  // Car detail
  "carDetail.backToList": "Back to list",
  "carDetail.specifications": "Specifications",
  "carDetail.features": "Features",
  "carDetail.description": "Description",
  "carDetail.financing": "Financing",
  "carDetail.monthlyPayment": "Monthly payment",
  "carDetail.applyNow": "Apply now",
  "carDetail.contactUs": "Contact us",

  // Leasing page
  "leasing.title": "Leasing",
  "leasing.description": "Car leasing with the best conditions",

  // Old car purchase keys (kept for backwards compatibility with old components)
  "carPurchase.title": "Car Purchase",
  "carPurchase.description": "We buy cars quickly and at the best price",
  "carPurchase.instantEval": "Instant Evaluation",
  "carPurchase.instantEvalDesc": "Get your car evaluation in minutes",
  "carPurchase.bestPrice": "Best Price",
  "carPurchase.bestPriceDesc": "We offer competitive prices for your car",
  "carPurchase.quickDeal": "Quick Deal",
  "carPurchase.quickDealDesc": "The whole process takes just a few hours",
  "carPurchase.safeDeal": "Safe Deal",
  "carPurchase.safeDealDesc": "Official transaction with all documents",
  "carPurchase.howItWorks": "How It Works",
  "carPurchase.step1": "Submit a request",
  "carPurchase.step1Desc": "Fill out the form with car details",
  "carPurchase.step2": "Get evaluation",
  "carPurchase.step2Desc": "Our specialists will evaluate your car",
  "carPurchase.step3": "Make a deal",
  "carPurchase.step3Desc": "Once price is agreed, we close the deal",
  "carPurchase.step4": "Get paid",
  "carPurchase.step4Desc": "Money is transferred immediately",
  "carPurchase.orCall": "or call",

  // About page
  "about.title": "About Us",
  "about.description": "Reliable car financing partner",

  // Car catalog
  "catalog.title": "Car Catalog",
  "catalog.filter": "Filter",
  "catalog.clearFilters": "Clear filters",
  "catalog.noResults": "No cars found",
  "catalog.adjustFilters": "Adjust filters or",
  "catalog.viewAll": "view all",

  // Loan form
  "loan.title": "Loan Application",
  "loan.name": "Full Name",
  "loan.email": "Email",
  "loan.phone": "Phone",
  "loan.amount": "Loan amount",
  "loan.term": "Term",
  "loan.monthlyPayment": "Monthly payment",
  "loan.submit": "Submit application",
  "loan.submitting": "Submitting...",
  "loan.success": "Application submitted successfully!",

  // Cookie consent
  "cookie.message": "This website uses cookies to improve your experience.",
  "cookie.title": "Cookie Policy",
  "cookie.description": "We use cookies to enhance your browsing experience and analyze website traffic. By accepting, you help us improve our services.",
  "cookie.accept": "Accept",
  "cookie.decline": "Decline",

  // Loan calculator
  "loanCalc.title": "Leasing Calculator",
  "loanCalc.carPrice": "Car price",
  "loanCalc.downPayment": "Down payment",
  "loanCalc.noDownPayment": "No down payment",
  "loanCalc.customAmount": "Other amount",
  "loanCalc.enterAmount": "Enter amount",
  "loanCalc.period": "Period",
  "loanCalc.months": "mo.",
  "loanCalc.totalAmount": "Total amount",
  "loanCalc.monthlyPayment": "Monthly payment",
  "loanCalc.submitApplication": "Submit leasing application",
  "loanCalc.disclaimer": "* Calculation is approximate. Exact terms will be provided after submitting an application. Annual interest rate:",
  "loanCalc.from": "from",
  "loanCalc.perMonth": "/mo.",

  // Loan application form
  "loanApp.title": "Loan Application",
  "loanApp.name": "Full Name",
  "loanApp.namePlaceholder": "John Doe",
  "loanApp.email": "Email",
  "loanApp.emailPlaceholder": "john@example.com",
  "loanApp.phone": "Phone",
  "loanApp.phonePlaceholder": "+370 600 00000",
  "loanApp.leasingData": "Leasing details:",
  "loanApp.car": "Car:",
  "loanApp.amount": "Amount:",
  "loanApp.term": "Term:",
  "loanApp.monthlyPayment": "Monthly payment:",
  "loanApp.submit": "Submit application",
  "loanApp.submitting": "Submitting...",
  "loanApp.success": "Application submitted!",
  "loanApp.successDesc": "We will contact you shortly via email or phone.",
  "loanApp.error": "Error submitting application. Please try again.",

  // Leasing page
  "leasing.heroTitle": "Financing",
  "leasing.heroDesc": "Fast and simple process – get financing within 24 hours with the lowest interest rates on the market",
  "leasing.calcTitle": "Calculate your monthly payment",
  "leasing.calcDesc": "Use the calculator to find out your approximate monthly payment",
  "leasing.loanCalculator": "Loan Calculator",
  "leasing.loanAmount": "Loan amount",
  "leasing.term": "Term",
  "leasing.monthlyFrom": "Monthly payment from",
  "leasing.calculatorTooltip": "Calculated with 6.9% annual interest + €9.50 monthly fee.",
  "leasing.totalReturn": "Total amount to return:",
  "leasing.conditions": "Loan Conditions",
  "leasing.annualRate": "Annual interest rate",
  "leasing.loanSum": "Loan amount",
  "leasing.termRange": "Term",
  "leasing.adminFee": "Monthly admin fee",
  "leasing.contractFee": "Contract fee",
  "leasing.bvkmn": "APR from",
  "leasing.bvkmnTooltip": "Annual Percentage Rate of Charge.",
  "leasing.submitApplication": "Submit application",
  "leasing.howItWorks": "How does financing work?",
  "leasing.step1": "Fill out application",
  "leasing.step1Desc": "Specify loan amount and term",
  "leasing.step2": "Get an offer",
  "leasing.step2Desc": "Response within 24 hours",
  "leasing.step3": "Sign the contract",
  "leasing.step3Desc": "Conveniently online",
  "leasing.step4": "Get the money",
  "leasing.step4Desc": "Directly to your account",
  "leasing.step": "Step",
  "leasing.whyChoose": "Why choose us?",
  "leasing.benefit1": "We compare terms",
  "leasing.benefit1Desc": "We find the best offer from multiple financial partners",
  "leasing.benefit2": "Low interest rates",
  "leasing.benefit2Desc": "Competitive interest rates from 6.9% annually",
  "leasing.benefit3": "Fast decision",
  "leasing.benefit3Desc": "Response within 24 hours, money in 1-2 days",
  "leasing.benefit4": "Individual consultation",
  "leasing.benefit4Desc": "We'll help you choose the most suitable financing option",
  "leasing.readyToStart": "Ready to start?",
  "leasing.readyToStartDesc": "Fill out the application now and get an offer within 24 hours",
  "leasing.getOffer": "Get an offer",

  // About page
  "about.heroTitle": "About Us",
  "about.heroDesc": "Your reliable partner in car financing",
  "about.whoWeAre": "Who are we?",
  "about.desc1": "We are a team that takes care not only of sales, but of the entire process – from assessing needs and searching for a car to smooth financing and document preparation. Transparency and clear communication are most important to us, so we explain everything simply and without hidden conditions.",
  "about.desc2": "We have a network of trusted partners in Lithuania and abroad, so we can offer both locally available cars and individual searches throughout Europe. We carefully check every car and adapt solutions to each client's situation.",
  "about.mission": "Our Mission",
  "about.missionDesc": "To give everyone the opportunity to purchase a car with convenient and flexible financing, ensuring transparency and reliability throughout the process.",
  "about.values": "Our Values",
  "about.valuesDesc": "Honesty, professionalism and customer satisfaction – these are the values that guide our daily work.",
  "about.whyChoose": "Why choose us?",
  "about.reliability": "Reliability",
  "about.reliabilityDesc": "All cars are inspected and come with warranty",
  "about.experience": "10+ years experience",
  "about.experienceDesc": "Long-term experience in the car market",
  "about.flexFinancing": "Flexible financing",
  "about.flexFinancingDesc": "Individual solutions for every client",
  "about.contactTitle": "Contact us",
  "about.contactDesc": "Have questions? Our team is ready to help!",
  "about.contact": "Contact",
  "about.getOffer": "Get an offer",
  "about.contactForm": "Contact us",
  "about.name": "Name",
  "about.yourName": "Your name",
  "about.email": "Email",
  "about.phone": "Phone",
  "about.message": "Message",
  "about.messagePlaceholder": "Your question or message...",
  "about.send": "Send message",
  "about.sending": "Sending...",
  "about.orContact": "Or contact us directly:",
  "about.messageSent": "Message sent!",
  "about.messageSentDesc": "We will contact you shortly.",
  "about.messageError": "Failed to send message. Please try again.",

  // Car purchase page
  "carPurchase.heroTitle": "Car Purchase",
  "carPurchase.heroDesc": "We buy all car brands quickly and fairly",
  "carPurchase.whySell": "Why sell to us?",
  "carPurchase.whySellDesc": "We buy cars quickly, fairly and at the best price",
  "carPurchase.bestPrices": "Best prices",
  "carPurchase.bestPricesDesc": "We offer competitive prices for your car",
  "carPurchase.fastProcess": "Fast process",
  "carPurchase.fastProcessDesc": "Car evaluation and purchase within 24 hours",
  "carPurchase.reliableDeal": "Reliable deal",
  "carPurchase.reliableDealDesc": "Transparent and safe car purchase process",
  "carPurchase.anyCondition": "Any condition",
  "carPurchase.anyConditionDesc": "We buy cars of all brands and any condition",
  "carPurchase.howWorks": "How does it work?",
  "carPurchase.simpleProcess": "Simple and fast process",
  "carPurchase.stepContact": "Contact us",
  "carPurchase.stepContactDesc": "Call us or fill out the online form with car details",
  "carPurchase.stepEval": "Evaluation",
  "carPurchase.stepEvalDesc": "Our specialist inspects the car and provides a price",
  "carPurchase.stepDeal": "Deal",
  "carPurchase.stepDealDesc": "Once price is agreed, we handle all formalities and pay",
  "carPurchase.wantToSell": "Want to sell your car?",
  "carPurchase.wantToSellDesc": "Contact us today and get the best offer!",
  "carPurchase.call": "Call us",
  "carPurchase.workingHours": "Working hours",
  "carPurchase.submitRequest": "Submit request",

  // Sell your car page
  "sellCar.heroTitle": "We'll sell your car",
  "sellCar.heroDesc": "Leave your car for sale with us and get maximum results without hassle. We'll take care of everything: from professional photos and listings to negotiations with buyers and paperwork.",
  "sellCar.submitRequest": "Submit request",
  "sellCar.howWorks": "How does it work?",
  "sellCar.step1": "Request",
  "sellCar.step1Desc": "Fill out the form with car information",
  "sellCar.step2": "Evaluation",
  "sellCar.step2Desc": "We contact you and evaluate the car",
  "sellCar.step3": "Sale",
  "sellCar.step3Desc": "We list, show and negotiate with buyers",
  "sellCar.step4": "Payment",
  "sellCar.step4Desc": "We handle documents and transfer money",
  "sellCar.whyChoose": "Why choose us?",
  "sellCar.professional": "Professional services",
  "sellCar.professionalDesc": "Professional photos, detailed listings and active marketing ensure your car reaches the widest audience possible.",
  "sellCar.timeSaved": "Time saved",
  "sellCar.timeSavedDesc": "No need to write listings yourself, answer messages, show the car or negotiate with buyers – we do it all.",
  "sellCar.safety": "Safety",
  "sellCar.safetyDesc": "Verified buyers, secure money transfer and complete document handling. You don't need to worry about fraud or bureaucracy.",
  "sellCar.bestPrice": "Best price",
  "sellCar.bestPriceDesc": "We help set the optimal price that ensures quick sale and maximum benefit for you. 10+ years of experience in the car market.",
  "sellCar.readyToSell": "Ready to sell?",
  "sellCar.readyToSellDesc": "Commission fee is negotiated individually, depending on the car and scope of services. Contact us and find out more!",

  // Common
  "common.loading": "Loading...",
  "common.error": "Error",
  "common.success": "Success!",
  "common.save": "Save",
  "common.cancel": "Cancel",
  "common.delete": "Delete",
  "common.edit": "Edit",
  "common.back": "Back",
  "common.next": "Next",
  "common.previous": "Previous",
  "common.search": "Search",
  "common.filter": "Filter",
  "common.all": "All",
  "common.yes": "Yes",
  "common.no": "No",
};

const translations: Record<Language, Record<string, string>> = { lt, en };

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("language");
      if (saved === "lt" || saved === "en") return saved;
    }
    return "lt";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
